version: "3"

services:

    namenode:
        image: bde2020/hadoop-namenode:2.0.0-hadoop3.1.1-java8
        container_name: namenode
        env_file:
          - ./hadoop.env
        environment:
          - CLUSTER_NAME=hive
        ports:
          - 50070:9870
          - 8020:9000
        volumes:
          - hadoop_namenode:/hadoop/dfs/name

    datanode1:
        image: bde2020/hadoop-datanode:2.0.0-hadoop3.1.1-java8
        container_name: datanode1
        environment:
          SERVICE_PRECONDITION: "namenode:9870"
        env_file:
          - ./hadoop.env
        ports:
          - 9864:9864
        volumes:
          - hadoop_datanode1:/hadoop/dfs/data

    datanode2:
        image: bde2020/hadoop-datanode:2.0.0-hadoop3.1.1-java8
        container_name: datanode2
        env_file:
          - ./hadoop.env
        environment:
          SERVICE_PRECONDITION: "namenode:9870 datanode1:9864"
        ports:
          - 9865:9864
        volumes:
          - hadoop_datanode2:/hadoop/dfs/data

    datanode3:
        image: bde2020/hadoop-datanode:2.0.0-hadoop3.1.1-java8
        container_name: datanode3
        env_file:
          - ./hadoop.env
        environment:
          SERVICE_PRECONDITION: "namenode:9870 datanode2:9864"
        ports:
          - 9866:9864
        volumes:
          - hadoop_datanode3:/hadoop/dfs/data

    resourcemanager:
        image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.1.1-java8
        container_name: resourcemanager
        environment:
          SERVICE_PRECONDITION: "namenode:9870 datanode1:9864 datanode2:9864 datanode3:9864 "
        env_file:
          - ./hadoop.env
        ports:
          - 8088:8088
          - 8888:8888

    nodemanager1:
        image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.1.1-java8
        container_name: nodemanager
        env_file:
          - ./hadoop.env
        environment:
          SERVICE_PRECONDITION: "namenode:9870 datanode1:9864 resourcemanager:8088"
        ports:
          - 8042:8042

    historyserver:
        image: bde2020/hadoop-historyserver:2.0.0-hadoop3.1.1-java8
        container_name: historyserver
        ports:
          - 8188:8188
        env_file:
          - ./hadoop.env
        environment:
          SERVICE_PRECONDITION: "namenode:9870 datanode1:9864 resourcemanager:8088"
        volumes:
          - hadoop_historyserver:/hadoop/yarn/timeline


volumes:
  hadoop_namenode:
  hadoop_datanode1:
  hadoop_datanode2:
  hadoop_datanode3:
  hadoop_historyserver:
